version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - "pip install '.[dev]'"
      - "mkdocs build"

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false